# MySQL.  Versions 4.1 and 5.0 are recommended.
#
# Install the MySQL driver:
#   gem install mysql
# On Mac OS X:
#   sudo gem install mysql -- --with-mysql-dir=/usr/local/mysql
# On Mac OS X Leopard:
#   sudo env ARCHFLAGS="-arch i386" gem install mysql -- --with-mysql-config=/usr/local/mysql/bin/mysql_config
#       This sets the ARCHFLAGS environment variable to your native architecture
# On Windows:
#   gem install mysql
#       Choose the win32 build.
#       Install MySQL and put its /bin directory on your path.
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html

<%
$myhost = 'localhost'

$myadapter = if RUBY_PLATFORM =~ /java/ then "jdbc" else "mysql" end

def file(*choices)
    choices.each { |name| return name if File.exist?(name) }
    choices.last
end

$mysocket = file '/var/run/mysqld/mysqld.sock',
  '/opt/local/var/run/mysql5/mysqld.sock', '/tmp/mysql.sock'

def db(phase) "sharequiz_#{phase}" end

def url(phase) "jdbc:mysql://#{$myhost}:3306/#{db(phase)}" end
%>

common: &common
      host: <%= $myhost %>
      adapter: <%= $myadapter %>
      pool: 5
      socket: <%= $mysocket %>
      driver: com.mysql.jdbc.Driver
      username: root
      password:

development:
      database: <%= db 'development' %>
      url: <%= url 'development' %>
      <<: *common

test:
      database: <%= db 'test' %>
      url: <%= url 'test' %>
      <<: *common

production:
      database: <%= db 'production' %>
      url: <%= url 'production' %>
      <<: *common
