# -*- coding: utf-8 -*-
class AddQueryData < ActiveRecord::Migration
  def self.up
    create_query 'Greetings', 'bonjour', 'goddag; hej', nil
    create_query 'Greetings', 'comment', 'hur', nil
    create_query 'Paris', 'une rue', 'street', nil
    create_query 'Paris', 'une maison', 'house', nil
    create_query 'Test', 'man; människa', '人', nil
    create_query 'Test', 'barn', '孩子', nil
    create_query 'CPod A1: Enkla hälsningsfraser', '我', 'jag; mig', 'wǒ'
    create_query 'CPod A1: Enkla hälsningsfraser', '你', 'du; dig', 'nǐ'
    create_query 'CPod A1: Enkla hälsningsfraser', '他', 'han; honom', 'tā'
    create_query 'CPod A1: Enkla hälsningsfraser', '她', 'hon; henne', 'tā'
    create_query 'CPod A1: Enkla hälsningsfraser', '它', 'den; det', 'tā'
    create_query 'CPod A1: Enkla hälsningsfraser', '我们', 'vi', 'wǒ men'
    create_query 'CPod A1: Enkla hälsningsfraser', '他们', 'de; dem', 'tā men'
    create_query 'CPod A1: Enkla hälsningsfraser', '很', 'mycket; väldigt', 'hěn'
    create_query 'CPod A1: Enkla hälsningsfraser', '好', 'bra', 'hǎo'
    create_query 'CPod A1: Enkla hälsningsfraser', '是', 'att vara; är', 'shì'
    create_query 'CPod A1: Enkla hälsningsfraser', '是(的); 对', 'ja', 'shì (de); duì'
    create_query 'CPod A1: Enkla hälsningsfraser', '很好', 'mycket bra', 'hěn hǎo'
    create_query 'CPod A1: Enkla hälsningsfraser', '谢谢', 'tack', 'xiè xiè'
    create_query 'CPod A1: Enkla hälsningsfraser', '中国人', 'kines; kinesisk person', 'zhōng guó rén'
    create_query 'CPod A1: Enkla hälsningsfraser', '中国', 'Kina', 'zhōng guó'
    create_query 'CPod A1: Enkla hälsningsfraser', '不是', 'nej; är inte', 'bú shì'
    create_query 'CPod A1: Enkla hälsningsfraser', '美国人', 'amerikan; amerikansk person', 'měi guó rén'
    create_query 'CPod A1: Enkla hälsningsfraser', '美国', 'Amerika', 'měi guó'
    create_query 'lesson1', 'bad', '坏', nil
    create_query 'CPod A2: Varifrån kommer du?', '不', 'nej; inte', 'bù'
    create_query 'CPod A2: Varifrån kommer du?', '不好', 'inte bra', 'bù hǎo'
    create_query 'CPod A2: Varifrån kommer du?', '忙', 'upptagen', 'máng'
    create_query 'CPod A2: Varifrån kommer du?', '国(家)', 'land; stat; nation', 'guó (jiā)'
    create_query 'CPod A2: Varifrån kommer du?', '英国', 'England', 'yīng guó'
    create_query 'CPod A2: Varifrån kommer du?', '法国', 'Frankrike', 'fǎ guó'
    create_query 'CPod A2: Varifrån kommer du?', '德国', 'Tyskland', 'dé guó'
    create_query 'CPod A2: Varifrån kommer du?', '累', 'trött', 'lèi'
    create_query 'CPod A2: Varifrån kommer du?', '对', 'ja; korrekt; rätt', 'duì'
    create_query 'CPod A3: Vart ska du gå?', '先生', 'herr', 'xiān sheng'
    create_query 'CPod A3: Vart ska du gå?', '小姐', 'fröken', 'xiǎo jie'
    create_query 'CPod A3: Vart ska du gå?', '也', 'också', 'yě'
    create_query 'CPod A3: Vart ska du gå?', '去', 'gå; fara; åka', 'qù'
    create_query 'CPod A3: Vart ska du gå?', '哪里', 'var', 'nǎ li'
    create_query 'CPod A3: Vart ska du gå?', '学校', 'skola', 'xué xiào'
    create_query 'CPod A4: Hur mår du?', '今天', 'idag', 'jīn tiān'
    create_query 'CPod A4: Hur mår du?', '马马虎虎', 'sådär; inget vidare', 'mǎ ma hū hu'
    create_query 'CPod A4: Hur mår du?', '真的', 'verkligen', 'zhēn de'
    create_query 'CPod A4: Hur mår du?', '为什么', 'varför', 'weì shén me'
    create_query 'CPod A4: Hur mår du?', '因为', 'för att; eftersom', 'yīn wéi'
    create_query 'CPod A5: Mer känslor med förklaringar', '昨天', 'igår', 'zuó tiān'
    create_query 'CPod A5: Mer känslor med förklaringar', '高兴; 开心', 'glad', 'gāo xìng'
    create_query 'CPod A5: Mer känslor med förklaringar', '难过', 'upprörd', 'nán guò'
    create_query 'CPod A5: Mer känslor med förklaringar', '对不起', 'ursäkta; förlåt', 'duì bù qǐ'
    create_query 'CPod A5: Mer känslor med förklaringar', '北京', 'Peking', 'běi jīng'
    create_query 'CPod A5: Mer känslor med förklaringar', '朱', 'Zhu', 'Zhū'
    create_query 'CPod A5: Mer känslor med förklaringar', '能', 'kunna; vara möjligt', 'néng'
    create_query 'CPod A5: Mer känslor med förklaringar', '说', 'säga; tala', 'shuō'
    create_query 'CPod A6: Kan du tala kinesiska?', '会', 'kunna; ha förmåga; veta hur man', 'huì'
    create_query 'CPod A6: Kan du tala kinesiska?', '普通', 'normal; standard', 'pǔ tōng'
    create_query 'CPod A6: Kan du tala kinesiska?', '一点;少', 'lite', 'yī diǎn'
    create_query 'CPod A6: Kan du tala kinesiska?', '一点点', 'litegrann', 'yī diǎn diǎn'
    create_query 'CPod A6: Kan du tala kinesiska?', '话', 'tal; språk', 'huà'
    create_query 'CPod A6: Kan du tala kinesiska?', '普通话', 'mandarin', 'pǔ tōng huà'
    create_query 'CPod A6: Kan du tala kinesiska?', '英语', 'engelska', 'yīng yǔ'
    create_query 'CPod A7: Kan du sjunga?', '唱歌', 'sjunga', 'chàng gē'
    create_query 'CPod A7: Kan du sjunga?', '但是', 'men', 'dàn shì'
    create_query 'CPod A7: Kan du sjunga?', '跳舞', 'dansa', 'tiào wǔ'
    create_query 'CPod A7: Kan du sjunga?', '听', 'höra; lyssna', 'tīng '
    create_query 'CPod A8: Herr Li', '李', 'Li', 'Lǐ'
    create_query 'CPod A8: Herr Li', '在', 'här; att vara (någonstans)', 'zài'
    create_query 'CPod A8: Herr Li', '不在', 'inte här', 'bú zài'
    create_query 'CPod A8: Herr Li', '在不在', 'här eller inte', 'zài bú zài'
    create_query 'CPod A8: Herr Li', '这里', 'här', 'zhè lǐ'
    create_query 'CPod A8: Herr Li', '办公室', 'kontor', 'bàn gōng shì'
    create_query 'CPod A8: Herr Li', '家', 'hem; familj', 'jiā'
    create_query 'CPod A9: Att handla', '想', 'tänka; vilja', 'xiǎng'
    create_query 'CPod A9: Att handla', '买', 'köpa', 'mǎi'
    create_query 'CPod A9: Att handla', '买东西', 'köpa något', 'mǎi dōng xi'
    create_query 'CPod A9: Att handla', '卖', 'sälja', 'mài'
    create_query 'CPod A9: Att handla', '什么', 'vad', 'shén me'
    create_query 'CPod A9: Att handla', '笔', 'penna', 'bǐ'
    create_query 'CPod A9: Att handla', '没有', 'finns inte; har inte', 'méi yǒu'
    create_query 'CPod A11: Att äta ute', '吃', 'äta', 'chī'
    create_query 'CPod A11: Att äta ute', '面', 'mjöl; nudlar; yta; ansikte', 'miàn'
    create_query 'CPod A11: Att äta ute', '好的', 'okej; bra', 'hǎo de'
    create_query 'CPod A11: Att äta ute', '等一下', 'vänta lite', 'děng yī xià'
    create_query 'CPod A11: Att äta ute', '饭', 'ris; mat', 'fàn'
    create_query 'CPod A11: Att äta ute', '吃饭', 'äta (mat); äta ris', 'chī fàn'
    create_query 'CPod A11: Att äta ute', '肉', 'kött', 'ròu'
    create_query 'CPod A11: Att äta ute', '牛肉', 'nötkött', 'niú ròu'
    create_query 'CPod A11: Att äta ute', '鸡肉', 'kyckling(kött)', 'jī ròu'
    create_query 'CPod A11: Att äta ute', '猪肉', 'griskött; fläsk(kött)', 'zhū ròu'
    create_query 'CPod A11: Att äta ute', '饭店', 'restaurang', 'fàn diàn'
    create_query 'CPod A11: Att äta ute', '点', 'punkt; beställa', 'diǎn'
    create_query 'CPod A12: Att beskriva mat', '水果', 'frukt', 'shuǐ guǒ'
    create_query 'CPod A12: Att beskriva mat', '好吃', 'god/gott (att äta)', 'hǎo chī'
    create_query 'CPod A13: Fröken Li tycker om att dricka', '喝', '(att) dricka', 'hē'
    create_query 'CPod A13: Fröken Li tycker om att dricka', '水', 'vatten', 'shuǐ'
    create_query 'CPod A13: Fröken Li tycker om att dricka', '酒', 'vin; alkohol', 'jiǔ'
    create_query 'CPod A13: Fröken Li tycker om att dricka', '果汁', 'juice', 'guǒ zhī'
    create_query 'CPod A13: Fröken Li tycker om att dricka', '喜欢', 'tycka om', 'xǐ huān'
    create_query 'CPod A13: Fröken Li tycker om att dricka', '好喝', 'god/gott (att dricka)', 'hǎo hē'
    create_query 'CPod A13: Fröken Li tycker om att dricka', '陈', 'Chen', 'Chén'
    create_query 'CPod A15: Att fira helger', '国庆节', 'nationaldag', 'guó qìng jié'
    create_query 'CPod A15: Att fira helger', '庆祝会', 'firande', 'qìng zhù huì'
    create_query 'CPod A15: Att fira helger', '春天', 'vår', 'chūn tiān'
    create_query 'CPod A15: Att fira helger', '月', 'månad', 'yuè'
    create_query 'CPod A15: Att fira helger', '十月', 'oktober', 'shí yuè'
    create_query 'CPod A15: Att fira helger', '七月', 'juli', 'qī yuè'
    create_query 'CPod A15: Att fira helger', '知道', 'veta', 'zhī dào'
    create_query 'CPod A15: Att fira helger', '明白;懂', 'förstå', 'míng bái; dǒng'
    create_query 'CPod A15: Att fira helger', '快乐', 'glad (att önska glad någonting)', 'kuài lè'
    create_query 'CPod A15: Att fira helger', '春节', 'vårfestival; kinesiskt nyår', 'chūn jié'
    create_query 'CPod A16: Dagar och månader', '日;天', 'dag', 'rì; tiān'
    create_query 'CPod A16: Dagar och månader', '星期一', 'måndag', 'xīng qī yī'
    create_query 'CPod A16: Dagar och månader', '一月', 'januari', 'yī yuè'
    create_query 'CPod A16: Dagar och månader', '二月', 'februari', 'èr yuè'
    create_query 'CPod A16: Dagar och månader', '十二月', 'december', 'shí èr yuè'
    create_query 'CPod A17: Inledande kundmöten', '叫', 'heta', 'jiào'
    create_query 'CPod A17: Inledande kundmöten', '姓', '(heta i) familjenamn', 'xìng'
    create_query 'CPod A17: Inledande kundmöten', '名', 'förnamn', 'míng'
    create_query 'CPod A17: Inledande kundmöten', '认识', 'vara bekant med; känna', 'rèn shi'
    create_query 'CPod A17: Inledande kundmöten', '我的名字是', 'mitt namn är', 'wǒ dē míng zì shì'
    create_query 'CPod A17: Inledande kundmöten', '这是', 'det här är', 'zhè shì'
    create_query 'CPod A17: Inledande kundmöten', '我的', 'min; mitt', 'wǒ dē'
    create_query 'CPod A17: Inledande kundmöten', '名片', 'visitkort', 'míng piàn'
    create_query 'CPod A18: Mobiltelefoner', '手机', 'mobiltelefon', 'shǒu jī'
    create_query 'CPod A18: Mobiltelefoner', '黑色', 'svart', 'hēi sè'
    create_query 'CPod A18: Mobiltelefoner', '蓝色', 'blå', 'lán sè'
    create_query 'CPod A18: Mobiltelefoner', '可以', 'kunna; få lov', 'kě yǐ'
    create_query 'CPod A18: Mobiltelefoner', '借', 'låna', 'jiè'
    create_query 'CPod A18: Mobiltelefoner', '没问题', 'inga problem', 'méi wèn tí'
    create_query 'CPod A19: Färger', '绿色', 'grön', 'lǜ sè'
    create_query 'CPod A19: Färger', '红色', 'röd', 'hóng sè'
    create_query 'CPod A19: Färger', '白色', 'vit', 'bái sè'
    create_query 'CPod A19: Färger', '黄色', 'gul', 'huáng sè'
    create_query 'CPod A19: Färger', '头发', 'hår', 'tóu fā'
    create_query 'CPod A19: Färger', '天', 'himmel; dag', 'tiān'
    create_query 'CPod A19: Färger', '胡椒粉', 'paprika', 'hú jiāo fěn'
    create_query 'CPod A19: Färger', '太多', 'för mycket', 'tài duō'
    create_query 'CPod A19: Färger', '白米饭', 'vitt ris', 'bái mǐ fàn'
    create_query 'CPod A19: Färger', '白领员工', 'tjänsteman', 'bái lǐng yuán gōng'
    create_query 'CPod A19: Färger', '(蓝领)工人', 'arbetare', '(lán lǐng) gōng rén'
    create_query 'CPod A19: Färger', '黄片', 'oanständig film; porrfilm', 'huáng piān'
    create_query 'CPod A19: Färger', '草', 'gräs', 'cǎo'
    create_query 'CPod A19: Färger', '青蛙', 'groda', 'qīng wā'
    create_query 'CPod A20: Shopping', '多少', 'hur mycket', 'duō shǎo'
    create_query 'CPod A20: Shopping', '钱', 'pengar', 'qián'
    create_query 'CPod A20: Shopping', '更多', '(ännu) mer', 'gèng duō'
    create_query 'CPod A20: Shopping', '更少', '(ännu) mindre', 'gèng shǎo'
    create_query 'CPod A20: Shopping', '贵', 'dyr', 'guì'
    create_query 'CPod A20: Shopping', '便宜', 'billig', 'pián yi'
    create_query 'CPod A20: Shopping', '非常便宜', 'mycket billig', 'fēi cháng pián yi'
    create_query 'CPod A20: Shopping', '这; 这个', 'den här', 'zhè'
    create_query 'CPod A20: Shopping', '那; 那个', 'den där', 'nà'
    create_query 'CPod A20: Shopping', '中国钱', 'kinesiska pengar', 'Zhōng guó qián'
    create_query 'CPod A20: Shopping', '人民币', 'RMB', 'rén mín bì'
    create_query 'CPod A20: Shopping', '元', 'yuan', 'yuán'
    create_query 'CPod A20: Shopping', '这支笔', 'den här pennan', 'zhè zhī bǐ'
    create_query 'CPod A20: Shopping', '十块', 'tio spänn; tio yuan', 'shí kuài'
    create_query 'CPod A21: Personlig information', '名字', 'namn', 'míng zi'
    create_query 'CPod A21: Personlig information', '住', '(att) bo', 'zhù'
    create_query 'CPod A21: Personlig information', '马路;路', 'väg; gata', 'mǎ lù'
    create_query 'CPod A21: Personlig information', '南京', 'Nanjing; Nanking', 'Nán jīng'
    create_query 'CPod A21: Personlig information', '南', 'söder; syd', 'nán'
    create_query 'CPod A21: Personlig information', '北', 'norr; nord', 'běi'
    create_query 'CPod A21: Personlig information', '你叫什么名字？', 'Vad heter du?; Vad är ditt namn?', 'Nǐ jiào shén me míng zì?'
    create_query 'CPod A21: Personlig information', '你呢？', 'Du då?', 'Nǐ ne?'
    create_query 'CPod A21: Personlig information', '你住在哪里？', 'Var bor du?', 'Nǐ zhù zài nǎ lǐ?'
    create_query 'CPod A21: Personlig information', '上海', 'Shanghai', 'Shàng hǎi'
    create_query 'CPod A22: Artiga presentationer', '请问', 'får jag fråga; ursäkta', 'qǐng wèn'
    create_query 'CPod A22: Artiga presentationer', '您', 'ni (artigt tilltal)', 'nín'
    create_query 'CPod A22: Artiga presentationer', '贵姓', 'ärofullt/ärorikt familjenamn', 'gùi xìng'
    create_query 'CPod A22: Artiga presentationer', '我姓', 'jag heter (i familjenamn)', 'wǒ xìng'
    create_query 'CPod A22: Artiga presentationer', '从', 'från; sedan', 'cóng'
    create_query 'CPod A22: Artiga presentationer', '从来', 'någonsin', 'cóng lái'
    create_query 'CPod A22: Artiga presentationer', '张先生', 'herr Zhang', 'Zhāng xiān shēng'
    create_query 'CPod A23: Ring mig!', '到', 'till; anlända; komma fram', 'dào'
    create_query 'CPod A23: Ring mig!', '什么时候; 几点', 'när; hur dags', 'shén me shí hòu; jǐ diǎn'
    create_query 'CPod A23: Ring mig!', '时间', 'tid', 'shí jiān'
    create_query 'CPod A23: Ring mig!', '回', 'återvända', 'huí'
    create_query 'CPod A23: Ring mig!', '回来', 'komma tillbaka', 'huí lái'
    create_query 'CPod A23: Ring mig!', '来', '(att) komma', 'lái'
    create_query 'CPod A23: Ring mig!', '早上', 'morgon', 'zǎo shàng'
    create_query 'CPod A23: Ring mig!', '中午', 'mitt på dagen; (vid) 12-tiden/tolvtiden', 'zhōng wǔ'
    create_query 'CPod A23: Ring mig!', '下午', 'eftermiddag', 'xià wǔ'
    create_query 'CPod A23: Ring mig!', '晚上', 'kväll', 'wǎn shàng'
    create_query 'CPod A23: Ring mig!', '上午', 'förmiddag', 'shàng wǔ'
    create_query 'CPod A23: Ring mig!', '他到北京去。', 'Han har åkt till Peking.', 'Tā dào běi jīng qù.'
    create_query 'CPod A23: Ring mig!', '他什么时候回来？', 'När kommer han tillbaka?', 'Tā shén me shí hòu huí lái?'
    create_query 'CPod A24: Vart är du på väg?', '地方', 'plats', 'dì fāng'
    create_query 'CPod A24: Vart är du på väg?', '百', 'hundra; 100', 'bǎi'
    create_query 'CPod A24: Vart är du på väg?', '号;码;号码;第;数', 'nummer', 'hào; mǎ; hào mǎ; dì; shù'
    create_query 'CPod A24: Vart är du på väg?', '公', 'allmän', 'gōng'
    create_query 'CPod A24: Vart är du på väg?', '公安', 'polisen', 'gōng ān'
    create_query 'CPod A24: Vart är du på väg?', '公司', 'företag', 'gōng sī'
    create_query 'CPod A24: Vart är du på väg?', '公共汽车', 'buss', 'gōng gòng qì chē'
    create_query 'CPod A24: Vart är du på väg?', '公用电话', 'allmän telefon', 'gōng yòng diàn huà'
    create_query 'CPod A25: Sevärdheter', '天安门广场', 'Himmelska fridens torg', 'tiān ān mén guǎng chǎng'
    create_query 'CPod A25: Sevärdheter', '离', 'från (om avstånd); lämna', 'lí'
    create_query 'CPod A25: Sevärdheter', '远', 'långt', 'yuǎn'
    create_query 'CPod A25: Sevärdheter', '怎么', 'hur', 'zěn me'
    create_query 'CPod A25: Sevärdheter', '直', 'rak; rakt', 'zhí'
    create_query 'CPod A25: Sevärdheter', '一直', 'rakt; alltid; hela tiden', 'yī zhí'
    create_query 'CPod A25: Sevärdheter', '走', 'gå', 'zǒu'
    create_query 'CPod A25: Sevärdheter', '再', 'sedan; igen; nästa', 'zài'
    create_query 'CPod A25: Sevärdheter', '右', 'höger', 'yòu'
    create_query 'CPod A25: Sevärdheter', '转', 'svänga', 'zhuǎn'
    create_query 'CPod A25: Sevärdheter', '门', 'dörr; port', 'mén'
    create_query 'CPod A25: Sevärdheter', '明天', 'i morgon', 'míng tiān'
    create_query 'CPod A25: Sevärdheter', '左', 'vänster', 'zuǒ'
    create_query 'CPod A25: Sevärdheter', '边', 'sida', 'biān'
    create_query 'CPod A25: Sevärdheter', '手', 'hand', 'shoǔ'
    create_query 'CPod A26: Vem är hon?', '谁', 'vem', 'shéi'
    create_query 'CPod A26: Vem är hon?', '朋友', 'vän', 'péng yŏu'
    create_query 'CPod A26: Vem är hon?', '漂亮; 美', 'vacker', 'piào liàng; měi'
    create_query 'CPod A26: Vem är hon?', '觉得', 'tycka; känna', 'jué de'
    create_query 'CPod A26: Vem är hon?', '女朋友', 'flickvän', 'nǚ péng yŏu'
    create_query 'CPod A27: I familjen', '妹妹', 'lillasyster', 'mèi mèi'
    create_query 'CPod A27: I familjen', '男朋友', 'pojkvän', 'nán péng yŏu'
    create_query 'CPod A27: I familjen', '好看', 'snygg', 'hăo kàn'
    create_query 'CPod A28: Tid för möte', '开会', '(att) ha (ett) möte', 'kāi huì'
    create_query 'CPod A28: Tid för möte', '五点钟', 'klockan fem/5', 'wǔ diǎn zhōng'
    create_query 'CPod A28: Tid för möte', '现在', 'nu', 'xiàn zài'
    create_query 'CPod A28: Tid för möte', '几点', 'när; hur dags; vad är klockan', 'jǐ diǎn'
    create_query 'CPod A28: Tid för möte', '半', 'halv', 'bàn'
    create_query 'CPod A28: Tid för möte', '一刻', '(en) kvart (över)', 'yī kè'
    create_query 'CPod A28: Tid för möte', '三刻', 'tre kvart (över)', 'sān kè'
    create_query 'CPod A28: Tid för möte', '手表', 'armbandsur; armbandsklocka', 'shǒu biǎo'
    create_query 'CPod A28: Tid för möte', '早', 'tidig', 'zǎo'
    create_query 'CPod A28: Tid för möte', '晚', 'sen', 'wǎn'
    create_query 'CPod A28: Tid för möte', '小时', 'timme; timma', 'xiǎo shí'
    create_query 'CPod A28: Tid för möte', '分钟', 'minut', 'fēn zhōng'
    create_query 'CPod A28: Tid för möte', '起床', 'stiga upp (ur sängen); gå upp', 'qǐ chuáng'
    create_query 'CPod A28: Tid för möte', '睡觉', 'sova', 'shuì jiào'
    create_query 'CPod A28: Tid för möte', '上班', 'gå till jobbet/arbetet; (börja) jobba/arbeta', 'shàng bān'
    create_query 'CPod A28: Tid för möte', '下班', 'sluta jobbet/jobba;sluta arbetet/arbeta', 'xià bān'
    create_query 'CPod A28: Tid för möte', '地铁', 'tunnelbana', 'dì tiě'
    create_query 'CPod A29: 9 till 5', '工作', 'arbeta; arbete', 'gōng zuò'
    create_query 'CPod A29: 9 till 5', '老师', 'lärare', 'lǎo shī'
    create_query 'CPod A29: 9 till 5', '大学', 'universitet', 'dà xué'
    create_query 'CPod A29: 9 till 5', '高中', 'gymnasium; högre mellanskola', 'gāo zhōng'
    create_query 'CPod A29: 9 till 5', '中学', 'högstadium; mellanskola', 'zhōng xué'
    create_query 'CPod A29: 9 till 5', '小学', 'småskola; låg- och mellanstadium', 'xiǎo xué'
    create_query 'CPod A29: 9 till 5', '岁', 'år (gammal)', 'suì'
    create_query 'CPod A29: 9 till 5', '老板', 'chef', 'lǎo bǎn'
    create_query 'CPod A29: 9 till 5', '医生', 'läkare; doktor', 'yī shēng'
    create_query 'CPod A29: 9 till 5', '工程师', 'ingenjör', 'gōng chéng shī'
    create_query 'CPod A29: 9 till 5', '工厂', 'fabrik', 'gōng chǎng'
    create_query 'CPod A29: 9 till 5', '秘书', 'sekreterare', 'mì shū'
    create_query 'CPod A29: 9 till 5', '卖票员', 'biljettförsäljare', 'mài piào yuán'
    create_query 'CPod A29: 9 till 5', '找', 'söka; finna', 'zhǎo'
    create_query 'CPod A29: 9 till 5', '只能', 'kan bara', 'zhǐ néng'
    create_query 'CPod A29: 9 till 5', '我是老师。', 'Jag är lärare.', 'Wǒ shì lǎo shī.'
    create_query 'CPod A29: 9 till 5', '我在大学工作。', 'Jag arbetar/jobbar på universitet(et).', 'Wǒ zài dà xué gōng zuò.'
    create_query 'CPod A30: Ansiktet', '服务员', 'kypare; servitör; servitris; serveringspersonal', 'fú wù yuán'
    create_query 'CPod A30: Ansiktet', '买单', '(betala) notan', 'mǎi dān'
    create_query 'CPod A30: Ansiktet', '付', 'betala', 'fù'
    create_query 'CPod A30: Ansiktet', '不行', 'kan inte; (det) går inte', 'bù xíng'
    create_query 'CPod A30: Ansiktet', '面子', 'ansikte (metaforiskt); prestige', 'miàn zi'
    create_query 'CPod A30: Ansiktet', '上次', 'förra gången', 'shàng cì'
    create_query 'CPod A30: Ansiktet', '下次', 'nästa gång', 'xià cì'
    create_query 'CPod A30: Ansiktet', '已经', 'redan', 'yǐ jīng'
    create_query 'CPod A30: Ansiktet', '哎哟', 'oj', 'ài yo'
    create_query 'CPod A30: Ansiktet', '信用卡', 'kreditkort', 'xìn yòng kǎ'
    create_query 'CPod A30: Ansiktet', '穷', 'fattig', 'qióng'
    create_query 'CPod A31: Toner del 2', '四声', 'fyra toner', 'sì shēng'
    create_query 'CPod A31: Toner del 2', '东方', 'östern; österlandet; orienten', 'dōng fāng'
    create_query 'CPod A31: Toner del 2', '洞房', 'sovrum', 'dòng fáng'
    create_query 'CPod A31: Toner del 2', '公里', 'kilometer; km', 'gōng lǐ'
    create_query 'CPod A31: Toner del 2', '巩俐', 'Gong Li', 'gǒng lì'
    create_query 'CPod A31: Toner del 2', '竹竿', 'bambukäpp; bambupinne', 'zhú gān'
    create_query 'CPod A31: Toner del 2', '猪肝', 'grislever', 'zhū gān'
    create_query 'CPod A32: Jag känner dig', '听说', 'höra (sägas)', 'tīng shuō'
    create_query 'CPod A32: Jag känner dig', '对吗？', 'Stämmer det?', 'Duì ma?'
    create_query 'CPod A32: Jag känner dig', '告诉', 'tala om (för)', 'gào sù'
    create_query 'CPod A32: Jag känner dig', '别人', 'andra (människor); någon', 'bié rén'
    create_query 'CPod A33: Jag måste gå', '一会儿', 'en stund (med nordlig dialekt)', 'yī huar'
    create_query 'CPod A33: Jag måste gå', '坐', 'sitta', 'zuò'
    create_query 'CPod A33: Jag måste gå', '我赶时间。', 'Jag har bråttom.', 'Wǒ gǎn shí jiān.'
    create_query 'CPod A33: Jag måste gå', '再见', 'hej då; vi ses (igen)', 'zài jiàn'
    create_query 'CPod A33: Jag måste gå', '明天见。', 'Vi ses i morgon.', 'Míng tiān jiàn.'
    create_query 'CPod A34: Familjeband', '一共', 'sammanlagt', 'yí gòng'
    create_query 'CPod A34: Familjeband', '三个人', 'tre/3 personer', 'sān gè rén'
    create_query 'CPod A34: Familjeband', '爸爸', 'pappa', 'bà ba'
    create_query 'CPod A34: Familjeband', '妈妈', 'mamma', 'mā ma'
    create_query 'CPod A34: Familjeband', '兄弟姐妹', 'syskon', 'xiōng dì jiě mèi'
    create_query 'CPod A34: Familjeband', '哥(哥); 兄', 'storebror', 'gē(ge); xiōng'
    create_query 'CPod A34: Familjeband', '弟弟', 'lillebror', 'dì di'
    create_query 'CPod A34: Familjeband', '姐姐', 'storasyster', 'jiě jie'
    create_query 'CPod A36: Yrkesliv', '律师', 'advokat', 'lǜ shī'
    create_query 'CPod A36: Yrkesliv', '方便', 'lämpligt; passande; bekväm; praktisk', 'fāng biàn'
    create_query 'CPod A36: Yrkesliv', '记者', 'journalist', 'jì zhě'
    create_query 'CPod A36: Yrkesliv', '问', '(att) fråga', 'wèn'
    create_query 'CPod A36: Yrkesliv', '问题', '(en) fråga; problem', 'wèn tí'
    create_query 'CPod B51: Nationaliteter', '澳大利亚', 'Australien', 'Ào dà lì yà'
    create_query 'CPod B50: Doggybag', '打包', 'slå in; lägga i (en) påse/doggybag', 'dǎ bāo'
    create_query 'CPod B50: Doggybag', '这些', 'de här; dessa', 'zhè xiē'
    create_query 'CPod B50: Doggybag', '汤', 'soppa', 'tāng '
    create_query 'CPod B49: Så pinsamt!', '这次', 'den här gången', 'zhè cì'
    create_query 'CPod B49: Så pinsamt!', '我请客', 'jag bjuder', 'wǒ qǐng kè'
    create_query 'CPod B49: Så pinsamt!', '不够', 'inte tillräckligt/nog', 'bú gòu'
    create_query 'CPod B49: Så pinsamt!', '丢脸; 丢面子', 'tappa ansiktet; förlora prestige', 'diū liǎn; diū miàn zi'
    create_query 'CPod B49: Så pinsamt!', '没关系', 'det spelar ingen roll', 'méi guān xì'
    create_query 'CPod B48: Husdjur', '养', 'föda upp', 'yǎng'
    create_query 'CPod B48: Husdjur', '宠物', 'husdjur', 'chǒng wù'
    create_query 'CPod B48: Husdjur', '猫', 'katt', 'māo'
    create_query 'CPod B48: Husdjur', '狗', 'hund', 'gǒu'
    create_query 'CPod B48: Husdjur', '宠', 'ta väl hand om; skämma bort', 'chǒng'
    create_query 'CPod B48: Husdjur', '物', 'varelse; kreatur', 'wù'
    create_query 'CPod B47: Solskydd', '防晒霜', 'solskyddskräm', 'fáng shài shuāng'
    create_query 'CPod B47: Solskydd', '样', 'sort/typ/stil', 'yàng'
    create_query 'CPod B47: Solskydd', '最好', 'bäst', 'zuì hǎo'
    create_query 'CPod B47: Solskydd', '什么样; 哪一种', 'vilken sort', 'shén me yang; nǎ yī zhǒng'
    create_query 'CPod B46: Att få en dejt', '明天晚上', 'i morgon kväll', 'míng tiān wǎn shang'
    create_query 'CPod B46: Att få en dejt', '有空', 'ha tid; vara ledig', 'yǒu kòng'
    create_query 'CPod B46: Att få en dejt', '一起', 'tillsammans', 'yī qǐ'
    create_query 'CPod B46: Att få en dejt', '东西', 'något; någonting', 'dōng xi'
    create_query 'CPod B45: Att gå till kyrkan', '信', 'tro på', 'xìn'
    create_query 'CPod B45: Att gå till kyrkan', '教', 'religion', 'jiào'
    create_query 'CPod B45: Att gå till kyrkan', '每', 'varje', 'měi'
    create_query 'CPod B45: Att gå till kyrkan', '都', 'alla; båda', 'dōu'
    create_query 'CPod B45: Att gå till kyrkan', '星期天', 'söndag', 'xīng qī tiān'
    create_query 'CPod B45: Att gå till kyrkan', '教堂', 'kyrka', 'jiào táng'
    create_query 'CPod B45: Att gå till kyrkan', '基督教', 'kristendom', 'jī dū jiào'
    create_query 'CPod B44: Att ladda ett kontantkort', '充值卡', 'kontantkort', 'chōng zhí kǎ'
    create_query 'CPod B44: Att ladda ett kontantkort', '够', 'tillräcklig(t); nog', 'gòu'
  end

  def self.down
    execute "DELETE FROM queries"
  end

  def self.create_query(lesson, question, answer, clue)
    lid = Lesson.find_by_name(lesson)
    if lid
      Query.create(:question => question, :answer => answer, :clue => clue,
                   :lesson_id => Lesson.find_by_name(lesson).id)
    else
      puts "'#{lesson}' not found"
    end
  end
end
